### PR TITLE
chore: fix addToDom selector

### LINKED ISSUE #367: addToDom utility function should only look for direct children
The `addToDom` function has a slight bug in it in that when it [tries to find `[data-kontra]` nodes](https://github.com/straker/kontra/blob/main/src/utils.js#L19) it does so assuming that they can only be a direct child of the container. However, if the dom is manipulated and a `[data-kontra]` node is moved and thus not a direct child of the container, the function errors with the message `"Node.insertBefore: Child to insert before is not a child of this node"`.

Instead the selector should be updated to only look for direct children of the container using the [:scope pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope#direct_children):

```js
container.querySelector(':scope > [data-kontra]:last-of-type') || canvas;
```

### PR DESCRIPTION
**Pull request by straker**
Also refactors `scrollParams` to `focusParams` as it wasn't named correctely.

Closes #367

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -18,10 +18,12 @@ export function addToDom(node, canvas) {
   node.setAttribute('data-kontra', '');
   if (container) {
     let target =
-      container.querySelector('[data-kontra]:last-of-type') || canvas;
-    container.insertBefore(node, target.nextSibling);
+      [
+        ...container.querySelectorAll(':scope > [data-kontra]')
```
Comment (straker) [inline src/utils.js:22]: `last-of-type` doesn't work on any selector, it only matches the last node name. So if the dom is

```
div.foo
div.foo
div
```

trying to do `.foo:last-of-type` doesn't work as `:last-of-type` first matches the last `div` of the group _then_ checks if it has the `.foo` class (which it doesn't so returns `null`)
